# Generated by Django 4.2.20 on 2025-04-14 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0002_job_benefits_job_education_job_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('current_title', models.CharField(blank=True, max_length=200, null=True)),
                ('experience_years', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(max_length=100)),
                ('notice_period', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('relocate', models.CharField(max_length=10)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('terms_agree', models.BooleanField(default=False)),
                ('future_contact', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Offered', 'Offered'), ('Accepted', 'Accepted')], default='Applied', max_length=20)),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app2.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_date'],
            },
        ),
    ]
