# Generated by Django 4.2.20 on 2025-04-15 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0003_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('companyImage', models.ImageField(blank=True, null=True, upload_to='CompanyImages/')),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('responsibilities', models.TextField(blank=True, help_text='Enter responsibilities separated by new lines')),
                ('requirements', models.TextField(blank=True, help_text='Enter requirements separated by new lines')),
                ('benefits', models.TextField(blank=True, help_text='Enter benefits separated by new lines')),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], default='Full-time', max_length=20)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalkInJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('companyImage', models.ImageField(blank=True, null=True, upload_to='CompanyImages/')),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('responsibilities', models.TextField(blank=True, help_text='Enter responsibilities separated by new lines')),
                ('requirements', models.TextField(blank=True, help_text='Enter requirements separated by new lines')),
                ('benefits', models.TextField(blank=True, help_text='Enter benefits separated by new lines')),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], default='Full-time', max_length=20)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalkInJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('current_title', models.CharField(blank=True, max_length=200, null=True)),
                ('experience_years', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(max_length=100)),
                ('notice_period', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('relocate', models.CharField(max_length=10)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('terms_agree', models.BooleanField(default=False)),
                ('future_contact', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Offered', 'Offered'), ('Accepted', 'Accepted')], default='Applied', max_length=20)),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app2.walkinjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkin_job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Walk-In Job Application',
                'verbose_name_plural': 'Walk-In Job Applications',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='RemoteJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('current_title', models.CharField(blank=True, max_length=200, null=True)),
                ('experience_years', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(max_length=100)),
                ('notice_period', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('relocate', models.CharField(max_length=10)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('terms_agree', models.BooleanField(default=False)),
                ('future_contact', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Offered', 'Offered'), ('Accepted', 'Accepted')], default='Applied', max_length=20)),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app2.remotejob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remote Job Application',
                'verbose_name_plural': 'Remote Job Applications',
                'ordering': ['-applied_date'],
            },
        ),
    ]
